//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRecord
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public int Quantity { get; set; }
        public double Profit { get; set; }
        public int IdEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MenuOfProduct MenuOfProduct { get; set; }
    }
}
